require 'rake'

ROOT_DIR = File.expand_path(File.dirname(__FILE__))
TESTS_DIR = File.join(ROOT_DIR, 'tests')
OUTPUT_DIR = File.join(ROOT_DIR, 'output')
require File.join(ROOT_DIR, '..', 'lib', 'unittest_js')

task :test => ['test:build', 'test:run']
namespace :test do
  desc 'Runs all the JavaScript unit tests and collects the results'
  task :run do
    testcases        = ENV['TESTCASES']
    browsers_to_test = ENV['BROWSERS'] && ENV['BROWSERS'].split(',')
    tests_to_run     = ENV['TESTS'] && ENV['TESTS'].split(',')
    runner           = UnittestJS::WEBrickRunner::Runner.new(:test_dir => OUTPUT_DIR)

    Dir[File.join(OUTPUT_DIR, '*_test.html')].each do |file|
      file = File.basename(file)
      test = file.sub('_test.html', '')
      unless tests_to_run && !tests_to_run.include?(test)
        runner.add_test(file, testcases)
      end
    end
    
    (browsers_to_test || UnittestJS::Browser::SUPPORTED).each do |browser|
        runner.add_browser(browser.to_sym)
    end
    
    trap('INT') { runner.teardown; exit }
    runner.run
  end
  
  task :build => [:clean] do
    builder = UnittestJS::Builder::SuiteBuilder.new({
      :input_dir => TESTS_DIR,
      :output_dir => OUTPUT_DIR
    })
    selected_tests = (ENV['TESTS'] || '').split(',')
    builder.collect(*selected_tests)
    builder.render
  end
  
  task :clean do
    UnittestJS::Builder.empty_dir!(OUTPUT_DIR)
  end
end

